title: "LEX'N'BOT"
open_ai_url: 'https://api.openai.com/v1/'
model_name: 'gpt-3.5-turbo-16k'
embeddings_model_name: 'text-embedding-ada-002'
vector_size: 1536
top_k_documents: 3

collections:
  - 'swiss-law'

avatars:
  human: 'ğŸ’â€â™€ï¸'
  ai: 'ğŸ¤–'

dataset:
  name: "brunnolou/swiss-code-of-obligations"
  collection: "code_of_obligations_en_paraphrase_multilingual"

db:
  host: "localhost"
  port: 6333